/*
 * Generated by utf8lex.
 *
 * Requires at runtime:
 *
 *     utf8lex
 *       https://github.com/jtienhaara/utf8lex
 *       Apache 2.0 license
 *
 *     utf8proc
 *       https://juliastrings.github.io/utf8proc
 *       MIT license
 *       Unicode data license
 *
 *     pcre2
 *       https://github.com/PCRE2Project/pcre2
 *       BSD license
 */
#include <stdio.h>

#include "utf8lex.h"

static utf8lex_rule_t *FIRST_RULE = NULL;
