/*
 * Generated by utf8lex.
 *
 * Requires at runtime:
 *
 *     utf8lex
 *       https://github.com/jtienhaara/utf8lex
 *       Apache 2.0 license
 *
 *     utf8proc
 *       https://juliastrings.github.io/utf8proc
 *       MIT license
 *       Unicode data license
 *
 *     pcre2
 *       https://github.com/PCRE2Project/pcre2
 *       BSD license
 *
 * This generated file is licensed according to the source code with which
 * it is distributed.  The template files from which this file derives
 * are public domain.
 */
#include <stdio.h>
#include <string.h>  // For strlen(), strcpy(), strcat, strncpy

#include "utf8lex.h"

// Static lexicon:
static utf8lex_definition_t *YY_FIRST_DEFINITION = NULL;
static utf8lex_rule_t *YY_FIRST_RULE = NULL;

// Runtime variables (non-thread-safe, of course):
static utf8lex_state_t YY_STATE;
static utf8lex_buffer_t YY_BUFFER;
static utf8lex_string_t YY_STRING;

static utf8lex_error_t yy_rules_init();
