/*
 * Generated by utf8lex.
 *
 * Requires at runtime:
 *
 *     utf8lex
 *       https://github.com/jtienhaara/utf8lex
 *       Apache 2.0 license
 *
 *     utf8proc
 *       https://juliastrings.github.io/utf8proc
 *       MIT license
 *       Unicode data license
 *
 *     pcre2
 *       https://github.com/PCRE2Project/pcre2
 *       BSD license
 *
 * This generated file is licensed according to the source code with which
 * it is distributed.  The template files (from which this generated file
 * derives) are public domain.
 */
#include <stdio.h>
#include <stdbool.h>  // for bool, true, false
#include <string.h>  // For strlen(), strcpy(), strcat, strncpy

#include "utf8lex.h"

// Static lexicon:
static utf8lex_definition_t *YY_FIRST_DEFINITION = NULL;
static utf8lex_rule_t *YY_FIRST_RULE = NULL;

// Runtime variables (non-thread-safe, of course):
static bool YY_IS_SETTINGS_INITIALIZED = false;
static utf8lex_settings_t YY_SETTINGS;
static utf8lex_state_t YY_STATE;
static utf8lex_buffer_t YY_BUFFER;
static utf8lex_string_t YY_STRING;

static utf8lex_error_t yy_rules_init();

// ------------------------------------------------------------------------
// Externally available functions:
// ------------------------------------------------------------------------

// Settings for lexing.
// (If not called, defaults will be used.)
extern utf8lex_error_t yylex_settings(
        utf8lex_settings_t *settings
        );

// Begin lexing.
extern utf8lex_error_t yylex_start(
        unsigned char *path
        );

// Lex with utf8 locations (including grapheme # etc).
extern int yyutf8lex(
        utf8lex_token_t *token_or_null,
        utf8lex_lloc_t *location_or_null
        );

// Traditional yylex(), with no location tracking.
extern int yylex();

// Finish lexing.
extern utf8lex_error_t yylex_end();
