name: Utf8lex Continuous Integration

env:
  UTF8LEX_LIBRARY_VERSION: "1.0.0"

permissions:
  contents: read
  packages: write

#
# Build (on push)
# - Compile utf8lex
# - Link into .so library
# - TODO Link into executable program
# - Upload .so, executable program to GitHub Packages
#
on:
  push: {}
  pull_request:
    types:
      - closed
      # TODO only on merge (requires if logic https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges)


jobs:
  # ====================================================================
  builder_container_image:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ./build
      BUILDER_IMAGE_FILE_BASE: "utf8lex-builder.${{github.ref_name}}"
      BUILDER_IMAGE_TAG: "utf8lex-builder:${{github.ref_name}}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #
      # https://docs.docker.com/build/ci/github-actions/cache/
      #
      - name: Restore container image
        id: builder-container-image-restore
        #
        # Never use actions/cache/restore:
        #
        #     https://github.com/orgs/community/discussions/27059#discussioncomment-10084333
        #
        uses: actions/cache@v4
        with:
          path: /tmp/${{env.BUILDER_IMAGE_FILE_BASE}}.tar
          key: utf8lex-builder-container-image-${{ hashFiles('build.Dockerfile') }}

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: qemu for multi-platform docker support
        if: steps.builder-container-image-restore.outputs.cache-hit != 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.builder-container-image-restore.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      #
      # Documentation:
      #     https://docs.docker.com/reference/cli/docker/buildx/build/
      #
      # For --output:
      #     https://docs.docker.com/build/exporters/
      #
      - name: Build utf8lex container for building and testing
        if: steps.builder-container-image-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{env.BUILD_DIR}}
          docker buildx build \
              --file build.Dockerfile \
              --output type=tar,dest=${{env.BUILD_DIR}}/${{env.BUILDER_IMAGE_FILE_BASE}}.tar \
              --platform=linux/amd64,linux/arm64,linux/mips64le,linux/ppc64le,linux/s390x \
              --tag ${{env.BUILDER_IMAGE_TAG}} \
              .

      #
      # Do not use actions/cache/save, it doesn't work.
      # Using actions/cache up above adds automagic.
      # We just copy the builder container image to where the
      # cache automagic expects to find it, in /tmp.
      #
      - name: Save builder container image for next time
        if: steps.builder-container-image-restore.outputs.cache-hit != 'true'
        id: builder-container-image-save
        run: |
          rm -rf /tmp/${{env.BUILDER_IMAGE_FILE_BASE}}.tar
          mv ${{env.BUILD_DIR}}/${{env.BUILDER_IMAGE_FILE_BASE}}.tar /tmp/${{env.BUILDER_IMAGE_FILE_BASE}}.tar
  # --------------------------------------------------------------------

  # ====================================================================
  shared_libraries:
    needs: builder_container_image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/mips64le
          - linux/ppc64le,linux/s390x
    env:
      BUILD_DIR: ./build
      BUILDER_IMAGE_FILE_BASE: "utf8lex-build.${{github.ref_name}}"
      BUILDER_IMAGE_TAG: "utf8lex-build:${{github.ref_name}}"
      SHARED_LIBRARIES_TAR_GZ: "utf8lex.${{github.ref_name}}.tar.gz"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #
      # https://docs.docker.com/build/ci/github-actions/cache/
      #
      - name: Restore container image
        id: builder-container-image-restore
        uses: actions/cache@v4
        with:
          path: /tmp/${{env.BUILDER_IMAGE_FILE_BASE}}.tar
          key: utf8lex-builder-container-image-${{ hashFiles('build.Dockerfile') }}

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: qemu for multi-platform docker run support
        uses: docker/setup-qemu-action@v3

      - name: Build utf8lex shared library
        run: |
          ls -l /tmp
          find /home/ 2> /dev/null || echo ignored errors
          docker import /tmp/${{env.BUILDER_IMAGE_FILE_BASE}}.tar \
              ${{env.BUILDER_IMAGE_TAG}}
          docker images
          sudo systemctl start docker
          mkdir -p ${{env.BUILD_DIR}}/${{matrix.platform}}
          #
          # docker run documentation:
          #     https://docs.docker.com/reference/cli/docker/container/run/
          #
          BUILD_DIR=${{env.BUILD_DIR}}/${{matrix.platform}} \
              docker run \
                  --rm \
                  --volume `pwd`:/utf8lex:rw \
                  ${{env.BUILDER_IMAGE_TAG}} \
                  ls /usr/bin/
          # !!!         /bin/sh -c 'ls /usr/bin/ && make all'
          find ${{env.BUILD_DIR}}/${{matrix.platform}} -type f

      - name: Tar utf8lex shared libraries
        run: |
          tar cvzf ${{env.BUILD_DIR}}//${{env.SHARED_LIBRARIES_TAR_GZ}} \
              ${{env.BUILD_DIR}}/*/*/*.so

      - name: Upload utf8lex libraries
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.SHARED_LIBRARIES_TAR_GZ}}
          path: ${{env.BUILD_DIR}}/${{env.SHARED_LIBRARIES_TAR_GZ}}
          if-no-files-found: error
          retention-days: 1
  # --------------------------------------------------------------------

#
# Unit test (on push)
# - Compile and link unit test programs
# - Run unit tests
#
# TODO
#

#
# Integration test (on push)
# - Compile and link integration test programs
# - Run integration tests
#
# TODO

#
# Release (on push tag)
# - Upload .so library, program to GitHub packages
# - Create a GitHub Release
#
# TODO
