name: Utf8lex Continuous Integration

permissions:
  contents: read
  packages: write

#
# Build (on push)
# - Compile utf8lex
# - Link into .so library
# - TODO Link into executable program
# - Upload .so, executable program to GitHub Packages
#
on:
  push: {}
  pull_request:
    types:
      - closed
      # TODO only on merge (requires if logic https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges)


jobs:
  # ====================================================================
  builder_container_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/mips64le
          - linux/ppc64le
          - linux/s390x
    env:
      BUILD_DIR: ./build
      BUILDER_IMAGE_BASE: "utf8lex-builder"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      #
      # https://docs.docker.com/build/ci/github-actions/cache/
      #
      - id: container-image-cache-restore
        name: Restore container image
        #
        # Never use actions/cache/restore:
        #
        #     https://github.com/orgs/community/discussions/27059#discussioncomment-10084333
        #
        uses: actions/cache@v4
        with:
          path: /tmp/builder/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz
          key: utf8lex-container-image-cache-${{ hashFiles('build.Dockerfile') }}

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - id: qemu-setup
        name: qemu for multi-platform docker support
        if: steps.container-image-cache-restore.outputs.cache-hit != 'true'
        uses: docker/setup-qemu-action@v3

      - id: docker-buildx-setup
        name: Set up Docker Buildx
        if: steps.container-image-cache-restore.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      #
      # Documentation:
      #     https://docs.docker.com/reference/cli/docker/buildx/build/
      #
      # For --output:
      #     https://docs.docker.com/build/exporters/
      #
      # Docker does not support loading multi-platform images from files (!):
      #     https://stackoverflow.com/questions/72945407/how-do-i-import-and-run-a-multi-platform-oci-image-in-docker-for-macos/73058421#73058421
      #
      # So we have to use the matrix to build multiple platforms.
      #
      - id: build-container-image
        name: Build utf8lex container for building and testing
        if: steps.container-image-cache-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{env.BUILD_DIR}}/${{matrix.platform}}
          docker buildx build \
              --file build.Dockerfile \
              --output type=oci,dest=${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar \
              --platform=${{matrix.platform}} \
              --tag ${{env.BUILDER_IMAGE_BASE}}:${{ hashFiles('build.Dockerfile') }} \
              .

      - id: gzip-builder-container-image
        name: Gzip utf8lex builder container image
        if: steps.container-image-cache-restore.outputs.cache-hit != 'true'
        run: |
          gzip ${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar

      #
      # Do not use actions/cache/save, it doesn't work.
      # Using actions/cache up above adds automagic.
      # We just copy the builder container image to where the
      # cache automagic expects to find it, in /tmp.
      #
      - id: container-image-cache-save
        name: Cache the built container image
        if: steps.container-image-cache-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/builder/${{matrix.platform}}
          rm -rf /tmp/builder/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz
          cp ${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz \
              /tmp/builder/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz

      #
      # https://github.com/actions/upload-artifact
      #
      - id: upload-container-image
        name: Upload the container image
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz
          path: /tmp/builder/
          if-no-files-found: error
          retention-days: 1
  # --------------------------------------------------------------------

  # ====================================================================
  shared_libraries:
    needs: builder_container_image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/mips64le
          - linux/ppc64le
          - linux/s390x
    env:
      BUILD_DIR: ./build
      BUILDER_IMAGE_BASE: "utf8lex-builder"
      SHARED_LIBRARY: "libutf8lex.so.${{github.ref_name}}"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: download-container-image
        name: Download container image
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz
          path: /tmp/builder/

      - id: copy-container-image
        name: Copy container image to build directory
        run: |
          mkdir -p ${{env.BUILD_DIR}}/${{matrix.platform}}
          cp /tmp/builder/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz \
              ${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz
          gunzip ${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar.gz

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - id: qemu-setup
        name: qemu for multi-platform docker run support
        uses: docker/setup-qemu-action@v3

      - id: build-utf8lex-so
        name: Build utf8lex shared library
        run: |
          echo "!!! 1"
          sudo systemctl start docker
          echo "!!! 2"
          docker image load \
              --input ${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar
          echo "!!! 3"
          docker images
          echo "!!! 4"
          rm ${{env.BUILD_DIR}}/${{matrix.platform}}/${{env.BUILDER_IMAGE_BASE}}.${{ hashFiles('build.Dockerfile') }}.tar
          echo "!!! 5"
          #
          # docker run documentation:
          #     https://docs.docker.com/reference/cli/docker/container/run/
          #
          BUILD_DIR=${{env.BUILD_DIR}}/${{matrix.platform}} \
              UTF8LEX_LIBRARY_VERSION=${{github.ref_name}} \
              docker run \
                  --rm \
                  --volume `pwd`:/utf8lex:rw \
                  ${{env.BUILDER_IMAGE_BASE}}:${{ hashFiles('build.Dockerfile') }} \
                  make all
          echo "!!! 6"
          find ${{env.BUILD_DIR}}/${{matrix.platform}} -type f
          echo "!!! 7"

      - id: tar-multiarch-utf8lex-so
        name: Tar utf8lex shared libraries
        run: |
          mkdir -p /tmp/so/${{matrix.platform}}
          cd ${{env.BUILD_DIR}}
          cp ${{matrix.platform}}/${{env.SHARED_LIBRARY}} \
              /tmp/so/${{matrix.platform}}/${{env.SHARED_LIBRARY}}

      - id: upload-multiarch-utf8lex-so
        name: Upload utf8lex libraries
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform}}/${{env.SHARED_LIBRARY}}
          path: /tmp/so/
          if-no-files-found: error
          retention-days: 1
  # --------------------------------------------------------------------

#
# Unit test (on push)
# - Compile and link unit test programs
# - Run unit tests
#
# TODO
#

#
# Integration test (on push)
# - Compile and link integration test programs
# - Run integration tests
#
# TODO

#
# Release (on push tag)
# - Upload .so library, program to GitHub packages
# - Create a GitHub Release
#
# TODO
